module.exoprts={
	"testMatch":["**/_tests_/**/*.js"],
    "moduleFileExtensions":[
        "js",
        "json",
        "vue"
    ],
    "transform":{
        ".*\\.vue$":"vue-jest",
        ".*\\.js$":"babel-jest"
    }
}